export const AppFont= {
        Opensans:'OpenSans-SemiBold',
        SansSemiBold:'OpenSans-SemiBold',
        SansMedium:'OpenSans_Condensed-Medium',
        RobotoMedium:'Roboto-Medium',
        Robotosmall:'Roboto-Light',
        sanslight:'OpenSans-Light',
        SansBold:'OpenSans-Bold',
        RobotoBold:'Roboto-Bold',
        RobotoRegular:'Roboto-Regular',
        JakartaSansBold:'PlusJakartaSans-Bold',
        JakartaSansLight:'PlusJakartaSans-Light',
        JakartaSansMedium:'PlusJakartaSans-Medium',
        JakartaSansRegular:'PlusJakartaSans-Regular',
        // RobotoRegular:'Roboto-Regular',
        // RobotoRegular:'Roboto-Regular',
        // RobotoRegular:'Roboto-Regular',
        // RobotoRegular:'Roboto-Regular',
}